### ISSUE TITLE
Some Fuses do not work on macOS/OpenCL

### ISSUE THREAD

**Issue by nmbr73** [nmbr73/Shadertoys#36]
The following Fuses currently do not work on macOS/OpenCL:

- [x]  TortureBlob (solve issue #34 first)
- [x] Rendezvous
- [x] DancyTreeDoodle
- [x] Legos
- [x] WalkingCubes (solve issue #34 first)
- [x] CrackerCars
- [x] WindingMengerTunnel (solve issues #34 and #35 first)

**Comment by J-i-P-i** [comment]
> The following Fuses currently do not work on Windows/OpenCL:

@nmbr73 : I think these Fuses are not work on Mac/OpenCl  😄

**Comment by nmbr73** [comment]
> @nmbr73 : I think these Fuses are not work on Mac/OpenCl

ah, yes - copypasta

**Comment by nmbr73** [comment]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/37710085/120109278-ff5d5b80-c168-11eb-863f-7ed5d71bf087.png">

**Comment by nmbr73** [comment]
DancyTreeDoodle solved with 04301b9a5a9316ff2911411db2d2c51e54471d42 ... and done ✅
